### ISSUE TITLE
Playback not working on iOS

### ISSUE THREAD

**Issue by skzap** [dtube/embed#15]
_From @chrishobcroft on March 8, 2018 4:45_

![received_10155567998793212](https://user-images.githubusercontent.com/2212651/37133484-e8c81ba2-2293-11e8-928c-7b9a8f436349.jpeg)

The same message experienced on two separate devices.

_Copied from original issue: dtube/production#12_

**Comment by skzap** [comment]
_From @chrishobcroft on March 8, 2018 4:47_

https://d.tube/#!/v/chrishobcroft/xtfpi6ay

**Comment by skzap** [comment]
_From @mrdev023 on March 13, 2018 9:44_

What export format did you use for video ?

**Comment by chrishobcroft** [comment]
Guys, you can also use Livepeer for transcoding for different players / browsers / devices / operating-systems etc.

It's all based on ffmpeg, so, whatever you can do in this, you can "outsource" to Livepeer, based on Ethereum.

If it is designed right, it can generate the transcoded version via Livepeer when a user first requests it, and write back into IPFS for you to serve later via D.Tube as a transcoded copy.

They can also solve your headache with 8k>4k>2k>1080p>720p>480p>360p>240p>144p because soon people are going to be uploading a lot of 4k / 8k video from Pro Cameras, and you're going to need a solution to how to serve this at 144p on Grandma's iPhone 4.

You can join our community at gitter.im/livepeer, where we've got people waiting to help you with this transcoding stuff... we're deployed on Rinkeby, and launching to mainnet of Ethereum.

I'm loving the prospect of integrating the Steem and Ethereum worlds through video.
